export const countryList =
    [
        {id : "1", label : "Afghanistan"},
        {id : "2", label : "Albanien"},
        {id : "3", label : "Algeria"},
        {id : "4", label : "Andorra"},
        {id : "5", label : "Angola"},
        {id : "6", label : "Antigua and Barbuda"},
        {id : "7", label : "Argentina"},
        {id : "8", label : "Armenia"},
        {id : "9", label : "Australia"},
        {id : "10", label : "Austria"},
        {id : "11", label : "Azerbaijan"},
        {id : "12", label : "Bahamas"},
        {id : "13", label : "Bahrain"},
        {id : "14", label : "Bangladesh"},
        {id : "15", label : "Barbados"},
        {id : "16", label : "Belarus"},
        {id : "17", label : "Belgium"},
        {id : "18", label : "Belize"},
        {id : "19", label : "Benin"},
        {id : "20", label : "Bhutan"},
        {id : "21", label : "Bolivia"},
        {id : "22", label : "Bosnia and Herzegovina"},
        {id : "23", label : "Botswana"},
        {id : "24", label : "Brazil"},
        {id : "25", label : "Brunei"},
        {id : "26", label : "Bulgaria"},
        {id : "27", label : "Burkina Faso"},
        {id : "28", label : "Burundi"},
        {id : "29", label : "Côte d'Ivoire"},
        {id : "30", label : "Cabo Verde"},
        {id : "31", label : "Cambodia"},
        {id : "32", label : "Cameroon"},
        {id : "33", label : "Canada"},
        {id : "34", label : "Central African Republic"},
        {id : "35", label : "Chad"},
        {id : "36", label : "Chile"},
        {id : "37", label : "China"},
        {id : "38", label : "Colombia"},
        {id : "39", label : "Comoros"},
        {id : "40", label : "Congo"},
        {id : "41", label : "Costa Rica"},
        {id : "42", label : "Croatia"},
        {id : "43", label : "Cuba"},
        {id : "44", label : "Cyprus"},
        {id : "45", label : "Czech Republic"},
        {id : "46", label : "Democratic Republic of the Congo"},
        {id : "47", label : "Denmark"},
        {id : "48", label : "Djibouti"},
        {id : "49", label : "Dominica"},
        {id : "50", label : "Dominican Republic"},
        {id : "51", label : "Ecuador"},
        {id : "52", label : "Egypt"},
        {id : "53", label : "El Salvador"},
        {id : "54", label : "Equatorial Guinea"},
        {id : "55", label : "Eritrea"},
        {id : "56", label : "Estonia"},
        {id : "57", label : "Eswatini"},
        {id : "58", label : "Ethiopia"},
        {id : "59", label : "Fiji"},
        {id : "60", label : "Finland"},
        {id : "61", label : "France"},
        {id : "62", label : "Gabon"},
        {id : "63", label : "Gambia"},
        {id : "64", label : "Georgia"},
        {id : "65", label : "Germany"},
        {id : "66", label : "Ghana"},
        {id : "67", label : "Greece"},
        {id : "68", label : "Grenada"},
        {id : "69", label : "Guatemala"},
        {id : "70", label : "Guinea"},
        {id : "71", label : "Guinea-Bissau"},
        {id : "72", label : "Guyana"},
        {id : "73", label : "Haiti"},
        {id : "74", label : "Holy See"},
        {id : "75", label : "Honduras"},
        {id : "76", label : "Hungary"},
        {id : "77", label : "Iceland"},
        {id : "78", label : "India"},
        {id : "79", label : "Indonesia"},
        {id : "80", label : "Iran"},
        {id : "81", label : "Iraq"},
        {id : "82", label : "Ireland"},
        {id : "83", label : "Israel"},
        {id : "84", label : "Italy"},
        {id : "85", label : "Jamaica"},
        {id : "86", label : "Japan"},
        {id : "87", label : "Jordan"},
        {id : "88", label : "Kazakhstan"},
        {id : "89", label : "Kenya"},
        {id : "90", label : "Kiribati"},
        {id : "91", label : "Kuwait"},
        {id : "92", label : "Kyrgyzstan"},
        {id : "93", label : "Laos"},
        {id : "94", label : "Latvia"},
        {id : "95", label : "Lebanon"},
        {id : "96", label : "Lesotho"},
        {id : "97", label : "Liberia"},
        {id : "98", label : "Libya"},
        {id : "99", label : "Liechtenstein"},
        {id : "100", label : "Lithuania"},
        {id : "101", label : "Luxembourg"},
        {id : "102", label : "Madagascar"},
        {id : "103", label : "Malawi"},
        {id : "104", label : "Malaysia"},
        {id : "105", label : "Maldives"},
        {id : "106", label : "Mali"},
        {id : "107", label : "Malta"},
        {id : "108", label : "Marshall Islands"},
        {id : "109", label : "Mauritania"},
        {id : "110", label : "Mauritius"},
        {id : "111", label : "Mexico"},
        {id : "112", label : "Micronesia"},
        {id : "113", label : "Moldova"},
        {id : "114", label : "Monaco"},
        {id : "115", label : "Mongolia"},
        {id : "116", label : "Montenegro"},
        {id : "117", label : "Morocco"},
        {id : "118", label : "Mozambique"},
        {id : "119", label : "Myanmar"},
        {id : "120", label : "Namibia"},
        {id : "121", label : "Nauru"},
        {id : "122", label : "Nepal"},
        {id : "123", label : "Netherlands"},
        {id : "124", label : "New Zealand"},
        {id : "125", label : "Nicaragua"},
        {id : "126", label : "Niger"},
        {id : "127", label : "Nigeria"},
        {id : "128", label : "North Korea"},
        {id : "129", label : "North Macedonia"},
        {id : "130", label : "Norway"},
        {id : "131", label : "Oman"},
        {id : "132", label : "Pakistan"},
        {id : "133", label : "Palau"},
        {id : "134", label : "Palestine"},
        {id : "135", label : "Panama"},
        {id : "136", label : "Papua New Guinea"},
        {id : "137", label : "Paraguay"},
        {id : "138", label : "Peru"},
        {id : "139", label : "Philippines"},
        {id : "140", label : "Poland"},
        {id : "141", label : "Portugal"},
        {id : "142", label : "Qatar"},
        {id : "143", label : "Romania"},
        {id : "144", label : "Russia"},
        {id : "145", label : "Rwanda"},
        {id : "146", label : "Saint Kitts and Nevis"},
        {id : "147", label : "Saint Lucia"},
        {id : "148", label : "Saint Vincent and the Grenadines"},
        {id : "149", label : "Samoa"},
        {id : "150", label : "San Marino"},
        {id : "151", label : "Sao Tome and Principe"},
        {id : "152", label : "Saudi Arabia"},
        {id : "153", label : "Senegal"},
        {id : "154", label : "Serbia"},
        {id : "155", label : "Seychelles"},
        {id : "156", label : "Sierra Leone"},
        {id : "157", label : "Singapore"},
        {id : "158", label : "Slovakia"},
        {id : "159", label : "Slovenia"},
        {id : "160", label : "Solomon Islands"},
        {id : "161", label : "Somalia"},
        {id : "162", label : "South Africa"},
        {id : "163", label : "South Korea"},
        {id : "164", label : "South Sudan"},
        {id : "165", label : "Spain"},
        {id : "166", label : "Sri Lanka"},
        {id : "167", label : "Sudan"},
        {id : "168", label : "Suriname"},
        {id : "169", label : "Sweden"},
        {id : "170", label : "Switzerland"},
        {id : "171", label : "Syria"},
        {id : "172", label : "Tajikistan"},
        {id : "173", label : "Tanzania"},
        {id : "174", label : "Thailand"},
        {id : "175", label : "Timor-Leste"},
        {id : "176", label : "Togo"},
        {id : "177", label : "Tonga"},
        {id : "178", label : "Trinidad and Tobago"},
        {id : "179", label : "Tunisia"},
        {id : "180", label : "Turkey"},
        {id : "181", label : "Turkmenistan"},
        {id : "182", label : "Tuvalu"},
        {id : "183", label : "Uganda"},
        {id : "184", label : "Ukraine"},
        {id : "185", label : "United Arab Emirates"},
        {id : "186", label : "United Kingdom"},
        {id : "187", label : "United States of America"},
        {id : "188", label : "Uruguay"},
        {id : "189", label : "Uzbekistan"},
        {id : "190", label : "Vanuatu"},
        {id : "191", label : "Venezuela"},
        {id : "192", label : "Vietnam"},
        {id : "193", label : "Yemen"},
        {id : "194", label : "Zambia"},
        {id : "195", label : "Zimbabwe"}
        ]